version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/apps/customer"
    schedule:
      interval: "weekly"

    labels:
      - "dependencies"

    commit-message:
      prefix: "build"

  - package-ecosystem: "pub"
    directory: "/apps/driver"
    schedule:
      interval: "weekly"

    labels:
      - "dependencies"

    commit-message:
      prefix: "build"